#!/bin/sh

# PROVIDE: mpr_collect
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="mpr_collect"
rcvar="mpr_collect_enable"

command="/usr/local/share/mpr_monitor/mpr_collect.sh"

pidfile="/var/run/${name}.pid"

start_cmd="${name}_start"
stop_cmd="${name}_stop"
status_cmd="${name}_status"

mpr_collect_start()
{
    echo "Starting ${name}."
    /usr/sbin/daemon -p ${pidfile} \
        -o /var/log/mpr_collect.log \
        ${command}
}

mpr_collect_stop()
{
    if [ -f ${pidfile} ]; then
        echo "Stopping ${name}."
        kill $(cat ${pidfile}) 2>/dev/null
        rm -f ${pidfile}
    else
        echo "${name} is not running."
    fi
}

mpr_collect_status()
{
    if [ -f ${pidfile} ] && kill -0 $(cat ${pidfile}) 2>/dev/null; then
        echo "${name} is running as pid $(cat ${pidfile})."
    else
        echo "${name} is not running."
    fi
}

load_rc_config $name
: ${mpr_collect_enable:="NO"}

run_rc_command "$1"
